#!/bin/bash

# DNS Setup Script for AItradingWeb3.com
# This script helps configure external domain forwarding

echo "🌐 AI Trading Web3 Platform - DNS Setup"
echo "========================================"
echo ""

# Get current Repl URL
REPL_URL="https://db1066b1-f9b5-425d-b211-cb0414c1c1c6.chatgptfive10.repl.co"
DOMAIN="AItradingWeb3.com"

echo "📊 Current Platform Status:"
echo "✅ Grid Trading Bot: Active"
echo "✅ Arbitrage Bot: Running across 4 exchanges"  
echo "✅ Auto Withdrawals: XRP transfers working"
echo "✅ Current URL: $REPL_URL"
echo ""

echo "🎯 Target Domain: $DOMAIN"
echo ""

echo "📋 Cloudflare Configuration Required:"
echo "======================================="
echo ""
echo "1. Page Rule 1:"
echo "   URL: *${DOMAIN}/*"
echo "   Setting: Forwarding URL (301)"
echo "   Destination: ${REPL_URL}/\$1"
echo ""
echo "2. Page Rule 2:"
echo "   URL: ${DOMAIN}"
echo "   Setting: Forwarding URL (301)"
echo "   Destination: ${REPL_URL}"
echo ""

echo "🔐 SSL Configuration:"
echo "===================="
echo "- Always Use HTTPS: ON"
echo "- SSL Mode: Flexible"
echo ""

echo "📝 DNS Records (Alternative Method):"
echo "===================================="
echo "Type: CNAME"
echo "Name: @"  
echo "Value: db1066b1-f9b5-425d-b211-cb0414c1c1c6.chatgptfive10.repl.co"
echo "TTL: Auto"
echo ""
echo "Type: CNAME"
echo "Name: www"
echo "Value: ${DOMAIN}"
echo "TTL: Auto"
echo ""

echo "⏰ Expected Timeline:"
echo "===================="
echo "- Domain purchase: 5 minutes"
echo "- Cloudflare setup: 15 minutes"
echo "- DNS propagation: 10-60 minutes"
echo "- Total time to live: Under 2 hours"
echo ""

echo "💰 Cost Estimate:"
echo "=================="
echo "- Domain registration: \$10-15/year"
echo "- Cloudflare: Free"
echo "- Total monthly: ~\$1"
echo ""

echo "🚀 Final Result:"
echo "================"
echo "Your AI Trading platform will be live at:"
echo "https://${DOMAIN}"
echo ""
echo "All current features preserved:"
echo "- Real-time trading across multiple exchanges"
echo "- Automatic profit withdrawal to XRP wallet"
echo "- 24/7 operation without interruption"
echo ""